-- Row counts for local vs Neon migration validation
-- Usage: psql "$DATABASE_URL" -f apps/foasis-backend/docs/sql/neon-row-counts.sql

SELECT 'User' AS table_name, COUNT(*)::bigint AS row_count FROM "User"
UNION ALL SELECT 'Organization', COUNT(*) FROM "Organization"
UNION ALL SELECT 'UserProfile', COUNT(*) FROM "UserProfile"
UNION ALL SELECT 'Team', COUNT(*) FROM "Team"
UNION ALL SELECT 'TeamMember', COUNT(*) FROM "TeamMember"
UNION ALL SELECT 'JoinRequest', COUNT(*) FROM "JoinRequest"
UNION ALL SELECT 'Proposal', COUNT(*) FROM "Proposal"
UNION ALL SELECT 'SupervisorRequest', COUNT(*) FROM "SupervisorRequest"
UNION ALL SELECT 'SupervisorInvitation', COUNT(*) FROM "SupervisorInvitation"
UNION ALL SELECT 'Notification', COUNT(*) FROM "Notification"
UNION ALL SELECT 'Meeting', COUNT(*) FROM "Meeting"
UNION ALL SELECT 'Announcement', COUNT(*) FROM "Announcement"
UNION ALL SELECT 'Deliverable', COUNT(*) FROM "Deliverable"
UNION ALL SELECT 'DeliverableDeadlineExtension', COUNT(*) FROM "DeliverableDeadlineExtension"
UNION ALL SELECT 'Submission', COUNT(*) FROM "Submission"
UNION ALL SELECT 'Milestone', COUNT(*) FROM "Milestone"
UNION ALL SELECT 'Task', COUNT(*) FROM "Task"
UNION ALL SELECT 'ActivityLog', COUNT(*) FROM "ActivityLog"
UNION ALL SELECT 'GlobalAnnouncement', COUNT(*) FROM "GlobalAnnouncement"
UNION ALL SELECT 'Evaluation', COUNT(*) FROM "Evaluation"
UNION ALL SELECT 'EvaluationPanel', COUNT(*) FROM "EvaluationPanel"
UNION ALL SELECT 'PanelEvaluator', COUNT(*) FROM "PanelEvaluator"
UNION ALL SELECT 'EvaluationAssignment', COUNT(*) FROM "EvaluationAssignment"
UNION ALL SELECT 'EvaluationResult', COUNT(*) FROM "EvaluationResult"
UNION ALL SELECT '_prisma_migrations', COUNT(*) FROM "_prisma_migrations"
ORDER BY 1;
